import type { Metadata } from "next";
import "./globals.css";
import { AppInitializer } from "@/components/AppInitializer";
import { SmoothScrolling } from "@/components/SmoothScrolling";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
        style={{ fontFamily: "'Switzer', sans-serif, 'style" }}
      >
        <SmoothScrolling>
          {children}
          <AppInitializer />
        </SmoothScrolling>
      </body>
    </html>
  );
}
